server:
  port: 8080
name: Jack
age: 18
content: "name: ${name}, age: ${age}"
person:
  name: haha
  age: 22
hello:
  msg: hi,hello world! I'm default.
info:
  head: head
  body: body
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
spring:
  thymeleaf:
    prefix: classpath:/templates/