SELECT ROW_NUMBER() OVER (ORDER BY A.GUID) AS ID
                                   ,A.GUID,A.WORK_NO,A.DISCHARGED_NO,A.BIZ_TYPE,dbo.F_NAME(A.BIZ_TYPE,'PARA_HFD_BIZTYPE') BIZ_TYPE_NAME
                                   ,A.BIZ_MODE,A.BIZ_MODE_NAME,A.I_E_MARK,dbo.F_NAME(A.I_E_MARK,'PARA_IE_MARK') I_E_MARK_NAME
                                   ,A.START_LAND,A.START_LAND_NAME,A.GOAL_LAND,A.GOAL_LAND_NAME,A.CAR_NO,A.CAR_WT
                                  ,A.IC_CODE,A.GATE_ID,A.GATE_ID2,A.F_CONTA_NO,A.F_CONTA_TYPE,A.F_CONTA_WT,A.A_CONTA_NO
                                  ,A.A_CONTA_TYPE,A.A_CONTA_WT,A.CARFRAME_NO,A.CARFRAME_TYPE,A.CARFRAME_TYPE_NAME
                                  ,A.CARFRAME_WT,A.GOODS_WT,A.FACT_WEIGHT,A.PACK_NO,A.BILL_NO,A.MAIN_GOODS
                                  ,A.INPUT_CODE,A.INPUT_NAME,A.TRADE_CODE,A.TRADE_NAME
                                  ,dbo.F_NAME(A.REGION_NAME,'PATA_REGION_CODE') REGION_CODE
                                  ,A.REGION_NAME,A.NOTE,A.APP_PERSON,A.APP_DATE
                                  ,dbo.F_NAME(A.CUSTOM_CODE,'BASE_CUSTOMS') CUSTOM_CODE
                                  ,A.CUSTOM_NAME,A.MASTER_CUSTOMS,A.MASTER_CUSTOMS_NAME
                                  ,dbo.F_NAME(A.STATUS,'PARA_HFD_STEP') STATUS,A.STATUS_NAME,A.FIT_MARK,A.B_STATUS
                                  ,A.B_STATUS_NAME,A.M_STATUS,A.M_STATUS_NAME,A.PRE_PORT_STATUS,A.PRE_PORT_STATUS_NAME
                                  ,A.PRE_PORT_DATE,dbo.F_NAME(A.PORT_STATUS,'PARA_HFD_PORTSTATUS') PORT_STATUS
                                  ,A.PORT_STATUS_NAME,A.PORT_DATE,A.HIT_STATUS,A.HIT_STATUS_NAME,A.CHECK_STATUS
                                  ,A.CHECK_STATUS_NAME,A.APPROVE_PERSON,A.APPROVE_DATE,A.PASS_TYPE,A.PASS_TYPE_NAME
                                  ,A.H2K_HIT_STATUS,A.H2K_HIT_STATUS_NAME,A.FIT_MARK_NAME,A.F_CONTA_TYPE_NAME
                                  ,A.A_CONTA_TYPE_NAME,A.ORDER_NUM,A.INPUT_DATE,A.INPUT_MAN
                                 FROM HFD_HEAD_PRE A WITH(NOLOCK) LEFT JOIN HFD_BODY_PRE B WITH(NOLOCK) ON A.GUID=B.GUID_HEAD   WHERE 1=1  AND A.STATUS IN ('HFD100500','HFD100440')  AND A.BIZ_MODE='B01' AND A.I_E_MARK='E' AND A.BIZ_MODE='B01' GROUP BY A.GUID,A.WORK_NO,A.DISCHARGED_NO,A.BIZ_TYPE,A.BIZ_TYPE
                                   ,A.BIZ_MODE,A.BIZ_MODE_NAME,A.I_E_MARK,A.I_E_MARK
                                   ,A.START_LAND,A.START_LAND_NAME,A.GOAL_LAND,A.GOAL_LAND_NAME,A.CAR_NO,A.CAR_WT
                                  ,A.IC_CODE,A.GATE_ID,A.GATE_ID2,A.F_CONTA_NO,A.F_CONTA_TYPE,A.F_CONTA_WT,A.A_CONTA_NO
                                  ,A.A_CONTA_TYPE,A.A_CONTA_WT,A.CARFRAME_NO,A.CARFRAME_TYPE,A.CARFRAME_TYPE_NAME
                                  ,A.CARFRAME_WT,A.GOODS_WT,A.FACT_WEIGHT,A.PACK_NO,A.BILL_NO,A.MAIN_GOODS
                                  ,A.INPUT_CODE,A.INPUT_NAME,A.TRADE_CODE,A.TRADE_NAME
                                  ,A.REGION_CODE,A.REGION_NAME,A.NOTE,A.APP_PERSON,A.APP_DATE
                                  ,A.CUSTOM_CODE,A.CUSTOM_NAME,A.MASTER_CUSTOMS,A.MASTER_CUSTOMS_NAME
                                  ,A.STATUS,A.STATUS_NAME,A.FIT_MARK,A.B_STATUS
                                  ,A.B_STATUS_NAME,A.M_STATUS,A.M_STATUS_NAME,A.PRE_PORT_STATUS,A.PRE_PORT_STATUS_NAME
                                  ,A.PRE_PORT_DATE,A.PORT_STATUS
                                  ,A.PORT_STATUS_NAME,A.PORT_DATE,A.HIT_STATUS,A.HIT_STATUS_NAME,A.CHECK_STATUS
                                  ,A.CHECK_STATUS_NAME,A.APPROVE_PERSON,A.APPROVE_DATE,A.PASS_TYPE,A.PASS_TYPE_NAME
                                  ,A.H2K_HIT_STATUS,A.H2K_HIT_STATUS_NAME,A.FIT_MARK_NAME,A.F_CONTA_TYPE_NAME
                                  ,A.A_CONTA_TYPE_NAME,A.ORDER_NUM,A.INPUT_DATE,A.INPUT_MAN